allowBuilds:
  '@adobe/css-tools': set this to true or false
  '@asamuzakjp/css-color': set this to true or false
  '@asamuzakjp/dom-selector': set this to true or false
  '@asamuzakjp/generational-cache': set this to true or false
  '@asamuzakjp/nwsapi': set this to true or false
  '@babel/code-frame': set this to true or false
  '@babel/helper-validator-identifier': set this to true or false
  '@babel/runtime': set this to true or false
  '@bramus/specificity': set this to true or false
  '@csstools/color-helpers': set this to true or false
  '@csstools/css-calc': set this to true or false
  '@csstools/css-color-parser': set this to true or false
  '@csstools/css-parser-algorithms': set this to true or false
  '@csstools/css-tokenizer': set this to true or false
  '@emnapi/core': set this to true or false
  '@emnapi/runtime': set this to true or false
  '@emnapi/wasi-threads': set this to true or false
  '@napi-rs/wasm-runtime': set this to true or false
  '@rolldown/binding-android-arm64': set this to true or false
  '@rolldown/binding-darwin-arm64': set this to true or false
  '@rolldown/binding-darwin-x64': set this to true or false
  '@rolldown/binding-freebsd-x64': set this to true or false
  '@rolldown/binding-linux-arm-gnueabihf': set this to true or false
  '@rolldown/binding-linux-arm64-gnu': set this to true or false
  '@rolldown/binding-linux-arm64-musl': set this to true or false
  '@rolldown/binding-linux-ppc64-gnu': set this to true or false
  '@rolldown/binding-linux-s390x-gnu': set this to true or false
  '@rolldown/binding-linux-x64-gnu': set this to true or false
  '@rolldown/binding-linux-x64-musl': set this to true or false
  '@rolldown/binding-openharmony-arm64': set this to true or false
  '@rolldown/binding-wasm32-wasi': set this to true or false
  '@rolldown/binding-win32-arm64-msvc': set this to true or false
  '@tauri-apps/cli-darwin-arm64': set this to true or false
  '@tauri-apps/cli-darwin-x64': set this to true or false
  '@tauri-apps/cli-linux-arm-gnueabihf': set this to true or false
  '@tauri-apps/cli-linux-arm64-gnu': set this to true or false
  '@tauri-apps/cli-linux-arm64-musl': set this to true or false
  '@tauri-apps/cli-linux-riscv64-gnu': set this to true or false
  '@tauri-apps/cli-linux-x64-gnu': set this to true or false
  '@tauri-apps/cli-linux-x64-musl': set this to true or false
  '@tauri-apps/cli-win32-arm64-msvc': set this to true or false
  '@tauri-apps/cli-win32-ia32-msvc': set this to true or false
  '@tybys/wasm-util': set this to true or false
  '@typescript/typescript-aix-ppc64': set this to true or false
  '@typescript/typescript-darwin-arm64': set this to true or false
  '@typescript/typescript-darwin-x64': set this to true or false
  '@typescript/typescript-freebsd-arm64': set this to true or false
  '@typescript/typescript-freebsd-x64': set this to true or false
  '@typescript/typescript-linux-arm': set this to true or false
  '@typescript/typescript-linux-arm64': set this to true or false
  '@typescript/typescript-linux-loong64': set this to true or false
  '@typescript/typescript-linux-mips64el': set this to true or false
  '@typescript/typescript-linux-ppc64': set this to true or false
  '@typescript/typescript-linux-riscv64': set this to true or false
  '@typescript/typescript-linux-s390x': set this to true or false
  '@typescript/typescript-linux-x64': set this to true or false
  '@typescript/typescript-netbsd-arm64': set this to true or false
  '@typescript/typescript-netbsd-x64': set this to true or false
  '@typescript/typescript-openbsd-arm64': set this to true or false
  '@typescript/typescript-openbsd-x64': set this to true or false
  '@typescript/typescript-sunos-x64': set this to true or false
  '@typescript/typescript-win32-arm64': set this to true or false
  bidi-js: set this to true or false
  css-tree: set this to true or false
  esbuild: true
  fsevents: set this to true or false
  is-potential-custom-element-name: set this to true or false
  js-tokens: set this to true or false
  lightningcss-android-arm64: set this to true or false
  lightningcss-darwin-arm64: set this to true or false
  lightningcss-darwin-x64: set this to true or false
  lightningcss-freebsd-x64: set this to true or false
  lightningcss-linux-arm-gnueabihf: set this to true or false
  lightningcss-linux-arm64-gnu: set this to true or false
  lightningcss-linux-arm64-musl: set this to true or false
  lightningcss-linux-x64-gnu: set this to true or false
  lightningcss-linux-x64-musl: set this to true or false
  lightningcss-win32-arm64-msvc: set this to true or false
  picocolors: set this to true or false
  tslib: set this to true or false
packages:
  - website
