/** Stable public entry. Implementations live in the responsibility modules below. */
export type { SelectionHit } from './canvas-input-state'
export {
  temporaryMoveToolAllowed,
  shouldUseTemporaryMoveTool,
  brushLineConnectionOverridesTemporaryMove,
  selectionInteractionOverridesTemporaryMove,
  temporaryMoveForCanvasInteractionAllowed,
  shouldUseTemporaryMoveForCanvasInteraction,
  temporaryMoveSuppressesToolPreview,
  cachedSelectionBoundarySegments
} from './canvas-input-state'
export {
  type CanvasPoint,
  type CanvasStrokePoint,
  type CanvasIsoGridStrokeEdge,
  type SelectionHandle,
  type SelectionRotationHandle,
  type SelectionShearHandle,
  type CanvasDragState,
  type MarqueeModifierMode,
  type MarqueeTemporaryCenterRestore
} from './canvas-input-contracts'
export {
  type PointerClientPoint,
  type CoalescedPointerEvent,
  type CanvasPointerDeviceEvent,
  isPenPointer,
  isPenEraserEvent,
  isPenBarrelButtonEvent,
  PEN_COMPATIBLE_MOUSE_SUPPRESSION_MS,
  type AdaptedPointerPressure,
  PointerPressureAdapter,
  coalescedPointerClientPoints,
  type BrushSpeedState,
  BRUSH_SPEED_EMA_TIME_CONSTANT_MS,
  BRUSH_SPEED_STOP_MS,
  BRUSH_SPEED_LIMIT,
  beginBrushSpeedTracking,
  updateBrushSpeedTracking
} from './canvas-input-pointer'
export {
  SELECTION_RESIZE_HIT_RADIUS,
  SELECTION_CORNER_RESIZE_HIT_RADIUS,
  SELECTION_CORNER_OUTWARD_RESIZE_HIT_RADIUS,
  SELECTION_PIVOT_HIT_RADIUS,
  selectionPivotHit,
  selectionPivotAtDragPoint,
  selectionPivotAfterResize,
  selectionResizeHit,
  rotationHandles,
  ROTATION_HANDLE_HIT_RADIUS,
  selectionShearHit,
  selectionRotationHit,
  selectionInteractionHit,
  selectionHitStartsContentMove,
  selectionTransformedInteractionHit,
  selectionFreeTransformHit,
  selectionFreeTransformContentHit
} from './canvas-input-hit-test'
export {
  layerMovePreviewActive,
  sampledForegroundColorToAdd,
  paletteSamplingShortcutStartsPrimarySample,
  type CachedSelectionTransformSource,
  cachedSelectionTransformSource,
  deferredSelectionCommitInvalidationRects,
  selectionTransformGeometrySource,
  resolveMarqueeModifierMode,
  revertCancelledCanvasDragPixelChanges,
  shouldPreserveLineAnchorAfterNoopDrag,
  selectionGestureMoved,
  type SelectionContentTransformKind,
  selectionTransformDeferredPreviewEnabled,
  deferredSelectionPreviewMaterializationRequired,
  deferredSelectionPreviewOwner,
  canvasGestureForPreview,
  brushPreviewAllowedDuringDrag,
  marqueePreviewTargetForDrag,
  drawingSizePreviewTargetForDrag,
  selectionOverlayMaskForDrag,
  type SelectionOverlayFrame,
  selectionOverlayFrameForDrag,
  selectionTransformModifiers,
  constrainFreeTransformCornerToAspectRatio,
  selectionTransformPreviewChanged,
  translatedSelectionRect,
  translatedSelectionTransformPreviewMask
} from './canvas-input-preview'
export {
  createCanvasPanDrag,
  viewDragClientDelta,
  restoreCanvasDragAfterPan,
  clampCanvasZoom,
  CANVAS_ZOOM_LEVELS,
  steppedCanvasZoom,
  normalizeCanvasWheelDelta,
  wheelCanvasZoom,
  zoomDragTarget,
  zoomDragModeForModifiers,
  isCanvasViewNavigationTool,
  playbackCanvasNavigationTool,
  isCanvasViewNavigationDrag,
  shouldStartCanvasPan
} from './canvas-input-navigation'
export {
  appendPolygonLassoVertex,
  isPendingCanvasPathGesture,
  appendCanvasPathStep,
  undoCanvasPathStep,
  redoCanvasPathStep,
  type PendingCanvasGestureHistoryController,
  registerPendingCanvasGestureHistory,
  consumePendingCanvasGestureHistory,
  shouldClosePolygonLasso,
  type PolygonPathRasterCache,
  createPolygonPathRasterCache,
  polygonLassoPreviewPoints,
  polygonLassoClosedPathPoints,
  shouldRestartFloatingSelectionForCopy,
  shouldReuseFloatingSelectionSourceForCopy,
  floatingSelectionCopyMode,
  finalizeMarqueeSelection,
  quickSelectCellSelection,
  quickSelectCellDragBounds,
  type QuickSelectionPress,
  isQuickSelectionSecondPress,
  marqueeSelectionCommit
} from './canvas-input-path'
export { type CanvasPointerState, CanvasInputState, undoActiveCanvasPathGesture } from './canvas-input-controller'
export {
  temporaryTransformOffset,
  createMarqueeResizeStart,
  centerMarqueeBoundsAtCreationPoint,
  beginTemporaryCenteredMarqueeResize,
  restoreTemporaryCenteredMarqueeResize,
  resizeRotatedMarqueeBounds,
  selectionRotationAngle,
  selectionMarqueeUsesConstraint,
  snapSelectionRotation,
  shapeBounds,
  centeredShapeBounds,
  constrainedTranslation,
  selectionMovePointerDelta,
  resizeSelectionBounds,
  resizeTransformedSelectionBounds
} from './canvas-input-resize'
