import { CYCLING_TOOL_SHORTCUT_IDS, QUICK_TOOL_SHORTCUT_IDS } from './tool-shortcut-ids'

export const DEFAULT_SHORTCUTS = {
  openHome: '',
  newDocument: 'Ctrl+N',
  openDocument: 'Ctrl+O',
  closeDocument: 'Ctrl+W',
  openProjectFolder: '',
  exportDocument: 'Ctrl+E',
  exportAllFrames: '',
  exportSpriteSheet: '',
  openTimelapse: '',
  openProjectInfo: '',
  openScriptFolder: '',
  'tool.pencil': 'B',
  'tool.pencil.quick': '',
  'tool.airbrush': 'J',
  'tool.airbrush.quick': '',
  'tool.eraser': 'E',
  'tool.magicEraser': 'Shift+E',
  'tool.magicEraser.quick': '',
  'tool.eraser.quick': '',
  'tool.selection': 'M',
  'tool.selection.quick': '',
  'tool.selection.ellipse': 'Shift+M',
  'tool.selection.ellipse.quick': '',
  'tool.move': 'V',
  'tool.move.quick': 'Ctrl',
  'tool.slice': 'Shift+C',
  'tool.slice.quick': '',
  'tool.shape': 'U',
  'tool.shape.quick': '',
  'tool.line': '',
  'tool.line.quick': '',
  'tool.text': 'T',
  'tool.text.quick': '',
  'tool.curve': '',
  'tool.curve.quick': '',
  'tool.shape.rectangleOutline': '',
  'tool.shape.rectangleOutline.quick': '',
  'tool.shape.rectangle': '',
  'tool.shape.rectangle.quick': '',
  'tool.shape.ellipseOutline': '',
  'tool.shape.ellipseOutline.quick': '',
  'tool.shape.ellipse': '',
  'tool.shape.ellipse.quick': '',
  'tool.shape.freeform': '',
  'tool.shape.freeform.quick': '',
  'tool.shape.polygon': '',
  'tool.shape.polygon.quick': '',
  'tool.fill': 'G',
  'tool.fill.quick': '',
  'tool.fill.gradient': 'Shift+G',
  'tool.fill.gradient.quick': '',
  'tool.eyedropper': 'I',
  'tool.eyedropper.quick': 'Alt',
  'tool.hand': 'H',
  'tool.hand.quick': 'Space',
  'tool.zoom': 'Z',
  'tool.zoom.quick': '',
  'tool.rotate': 'R',
  'tool.rotate.quick': '',
  'tool.smooth': '',
  'tool.smooth.quick': '',
  'tool.liquify': 'Y',
  'tool.liquify.quick': '',
  lasso: 'Q',
  'lasso.quick': '',
  polygonLasso: 'Shift+Q',
  'polygonLasso.quick': '',
  magic: 'W',
  'magic.quick': '',
  canvasResize: 'C',
  imageResize: 'Ctrl+Alt+I',
  transform: 'Ctrl+T',
  outline: 'Shift+O',
  quickOutline: 'Shift+S',
  outlineSelectionInside: 'S',
  adjustmentColorBalance: '',
  adjustmentBrightnessContrast: '',
  adjustmentHueSaturation: 'Ctrl+U',
  adjustmentCurves: 'Ctrl+M',
  openShortcutSettings: '',
  openPreferences: '',
  flipVertical: 'Shift+V',
  flipHorizontal: 'Shift+H',
  selectAll: 'Ctrl+A',
  invertSelection: 'Ctrl+Shift+I',
  deselect: 'Ctrl+D',
  deleteSelection: '',
  selectionModeReplace: '',
  selectionModeAdd: '',
  selectionModeSubtract: '',
  selectionModeIntersect: '',
  selectAllSlices: '',
  openAutoSlice: '',
  openSliceProperties: '',
  copy: 'Ctrl+C',
  copyMerged: 'Ctrl+Shift+C',
  rotateContent180: '',
  rotateContentCounterClockwise: '',
  rotateContentClockwise: '',
  centerContentBoth: '',
  centerContentHorizontal: '',
  centerContentVertical: '',
  invertColors: '',
  cut: 'Ctrl+X',
  paste: 'Ctrl+V',
  pasteAsNewLayer: 'Ctrl+Shift+V',
  pasteAsNewDocument: '',
  save: 'Ctrl+S',
  saveAs: 'Ctrl+Shift+S',
  undo: 'Ctrl+Z',
  redo: 'Ctrl+Shift+Z',
  relativeLuminance: 'Ctrl+Y',
  advancedMode: 'Ctrl+F',
  fillForeground: 'F',
  addForegroundToPalette: 'Alt+S',
  swapForegroundBackground: 'X',
  replaceColor: 'Shift+R',
  convertColorMode: '',
  convertColorModeRgba: '',
  convertColorModeIndexed: '',
  convertColorModeGrayscale: '',
  cropCanvas: '',
  trimCanvas: '',
  createBrushFromSelection: 'Ctrl+B',
  togglePaletteEditLock: '',
  extractPaletteColors: '',
  togglePaletteColorSync: '',
  reversePaletteColors: '',
  createPaletteGradient: '',
  createPaletteHueGradient: '',
  sortPaletteHue: '',
  sortPaletteSaturation: '',
  sortPaletteBrightness: '',
  sortPaletteLuminance: '',
  sortPaletteRed: '',
  sortPaletteGreen: '',
  sortPaletteBlue: '',
  sortPaletteAlpha: '',
  paletteSortAscending: '',
  paletteSortDescending: '',
  paletteSwatchTiny: '',
  paletteSwatchSmall: '',
  paletteSwatchMedium: '',
  paletteSwatchLarge: '',
  paletteSwatchHuge: '',
  savePalette: '',
  openPaletteFolder: '',
  refreshPalettes: '',
  newLayer: 'Shift+N',
  createLayerGroup: 'Ctrl+G',
  newTilemapLayer: '',
  newFreeTileLayer: '',
  newBackgroundLayer: '',
  createLinkedLayer: '',
  convertLayerToBackground: '',
  convertLayerToTilemap: '',
  convertLayerToRaster: '',
  openLayerProperties: '',
  openLayerStyles: '',
  toggleLayerStyles: '',
  copyLayerStyles: '',
  pasteLayerStyles: '',
  clearLayerStyles: '',
  toggleLayerMask: '',
  toggleGroupMask: '',
  openLayerSettings: '',
  toggleClippingMask: 'Ctrl+Alt+G',
  toggleSelectedLayerVisibility: '',
  toggleSelectedLayerLock: '',
  toggleSelectedGroupCollapsed: '',
  duplicateLayer: '',
  mergeLayerDown: '',
  mergeSelectedLayers: '',
  mergeLayerGroup: '',
  mergeVisibleLayers: '',
  ungroupLayers: 'Ctrl+Shift+G',
  deleteLayer: 'Delete',
  mirrorView: 'Ctrl+Shift+M',
  mirrorViewVertical: 'Ctrl+Shift+Alt+M',
  toggleGrid: "Ctrl+Shift+'",
  toggleCustomGrid: "Ctrl+'",
  toggleIsoView: '',
  toggleSelectionOutline: 'Ctrl+H',
  toggleSliceOutlines: '',
  tileRepeatOff: '',
  tileRepeatBoth: '',
  tileRepeatX: '',
  tileRepeatY: '',
  rotateViewClockwise90: '',
  rotateViewCounterClockwise90: '',
  viewZoom100: '',
  viewZoom200: '',
  viewZoom400: '',
  viewZoom800: '',
  viewZoom3200: '',
  resetView: '',
  toggleFullscreen: 'F11',
  toggleColorPanel: '',
  togglePalettePanel: '',
  toggleLayersPanel: 'Tab',
  togglePreviewPanel: '',
  toggleTilesetPanel: '',
  toggleBrushLibraryPanel: '',
  popupColorPanel: '1',
  popupPalettePanel: '2',
  popupLayersPanel: '3',
  popupPreviewPanel: '4',
  popupTilesetPanel: '5',
  popupBrushLibraryPanel: '6',
  toggleTimeline: '',
  openGridSettings: '',
  openIsoViewSettings: '',
  toolRailLeft: '',
  toolRailRight: '',
  toolRailTop: '',
  toolRailBottom: '',
  saveWorkspaceLayout: '',
  resetWorkspaceLayout: '',
  openWorkspaceManager: '',
  openComponentLibrary: '',
  openLatestRelease: '',
  openAbout: '',
  brushSizeDecrease: '[',
  brushSizeIncrease: ']',
  copySelectionContent: 'Ctrl',
  copyLayerOnDrag: 'Alt',
  constrainAxis: 'Shift',
  addToSelection: 'Shift',
  proportionalSelectionTransform: 'Shift',
  integerSelectionScale: 'Ctrl',
  snapSelectionRotation: 'Shift',
  snapViewRotation: 'Shift',
  resetViewRotation: 'Ctrl',
  brushSizeAdjust: 'Ctrl+Alt',
  brushSizeWheelAdjust: 'Ctrl',
  lineConnectionMode: 'Shift',
  constrainLineDirections: 'Ctrl+Shift',
  brushShapeRound: 'Ctrl+1',
  brushShapeSquare: 'Ctrl+2',
  brushShapeLine: 'Ctrl+3',
  togglePerfectPixels: '',
  toggleContiguous: '',
  toggleSmartClosure: '',
  toggleRoundedCorners: '',
  toggleFixedRatio: '',
  toggleMoveAutoSelect: '',
  toggleSymmetryHorizontal: '',
  toggleSymmetryVertical: '',
  toggleSymmetryDiagonalUp: '',
  toggleSymmetryDiagonalDown: '',
  toggleSymmetryRotational: '',
  resetSymmetryCenter: '',
  tilemapModeEdit: '',
  tilemapModeCreate: '',
  tilemapModeHybrid: '',
  tilemapModePaint: '',
  freeTileModeEdit: '',
  freeTileModePaint: '',
  addFreeTileSource: '',
  deleteTilesetSelection: '',
  openFreeTileSourceProperties: '',
  showOnlyFreeTileInstance: '',
  openFreeTileInstanceProperties: '',
  rotateFreeTileInstance90: '',
  mirrorFreeTileInstanceHorizontal: '',
  mirrorFreeTileInstanceVertical: '',
  deleteFreeTileInstances: '',
  importBrushImage: '',
  createBrushFolder: '',
  openBrushFolder: '',
  refreshBrushLibrary: '',
  brushLibraryParentFolder: '',
  brushSwatchSmall: '',
  brushSwatchMedium: '',
  brushSwatchLarge: '',
  deleteBrushSelection: '',
  addAnimationFrame: 'Alt+N',
  addLinkedAnimationFrame: 'Alt+M',
  addBlankAnimationFrame: 'Alt+B',
  deleteAnimationFrame: 'Alt+C',
  enableAnimationFrames: '',
  disableAnimationFrames: '',
  toggleAnimationFramesDisabled: '',
  copyAnimationCel: 'Ctrl+D',
  copyAnimationFrames: '',
  pasteAnimationFrames: '',
  pasteAnimationCels: '',
  copyAnimationMasks: '',
  pasteAnimationMasks: '',
  connectAnimationCels: '',
  disconnectAnimationCels: '',
  connectAnimationMasks: '',
  disconnectAnimationMasks: '',
  toggleAnimationMask: '',
  createAnimationLoopSection: '',
  openAnimationFrameProperties: '',
  playAnimationLoopSection: '',
  openAnimationLoopSectionProperties: '',
  deleteAnimationLoopSection: '',
  openAnimationCelProperties: '',
  toggleAnimationPlayback: 'Enter',
  toggleOnionSkin: '',
  animationPlaybackOnce: '',
  animationPlaybackAll: '',
  animationPlaybackTag: '',
  toggleAnimationReturnToStart: '',
  animationPlaybackSpeed025: '',
  animationPlaybackSpeed050: '',
  animationPlaybackSpeed100: '',
  animationPlaybackSpeed150: '',
  animationPlaybackSpeed200: '',
  animationPlaybackSpeed300: '',
  previousAnimationFrame: '',
  nextAnimationFrame: ''
} as const

export type ShortcutId = keyof typeof DEFAULT_SHORTCUTS

export type ShortcutMap = Record<string, string>

export type ShortcutBindings = Record<ShortcutId, string[]>

export interface ShortcutSettingsFile {
  format: 'moonsprite-shortcuts'
  version: 2
  bindings: Partial<Record<ShortcutId, string[]>>
}

const TOOL_SHORTCUT_GROUP = CYCLING_TOOL_SHORTCUT_IDS.flatMap((id, index) => [id, QUICK_TOOL_SHORTCUT_IDS[index]]) as ShortcutId[]

export const SHORTCUT_GROUPS = {
  file: ['openHome', 'newDocument', 'openDocument', 'closeDocument', 'openProjectInfo', 'save', 'saveAs', 'exportDocument', 'exportAllFrames', 'exportSpriteSheet', 'openProjectFolder', 'openTimelapse', 'openScriptFolder'],
  edit: ['undo', 'redo', 'cut', 'copy', 'copyMerged', 'paste', 'pasteAsNewLayer', 'pasteAsNewDocument', 'deleteLayer', 'deleteSelection', 'fillForeground', 'quickOutline', 'outline', 'outlineSelectionInside', 'transform', 'rotateContent180', 'rotateContentCounterClockwise', 'rotateContentClockwise', 'flipHorizontal', 'flipVertical', 'centerContentBoth', 'centerContentHorizontal', 'centerContentVertical', 'replaceColor', 'invertColors', 'adjustmentColorBalance', 'adjustmentBrightnessContrast', 'adjustmentHueSaturation', 'adjustmentCurves'],
  selection: ['selectAll', 'invertSelection', 'deselect', 'toggleSelectionOutline', 'createBrushFromSelection', 'selectionModeReplace', 'selectionModeAdd', 'selectionModeSubtract', 'selectionModeIntersect', 'selectAllSlices', 'openAutoSlice', 'openSliceProperties'],
  image: ['canvasResize', 'imageResize', 'convertColorMode', 'convertColorModeRgba', 'convertColorModeIndexed', 'convertColorModeGrayscale', 'cropCanvas', 'trimCanvas'],
  color: ['addForegroundToPalette', 'swapForegroundBackground', 'togglePaletteEditLock', 'extractPaletteColors', 'togglePaletteColorSync', 'reversePaletteColors', 'createPaletteGradient', 'createPaletteHueGradient', 'sortPaletteHue', 'sortPaletteSaturation', 'sortPaletteBrightness', 'sortPaletteLuminance', 'sortPaletteRed', 'sortPaletteGreen', 'sortPaletteBlue', 'sortPaletteAlpha', 'paletteSortAscending', 'paletteSortDescending', 'paletteSwatchTiny', 'paletteSwatchSmall', 'paletteSwatchMedium', 'paletteSwatchLarge', 'paletteSwatchHuge', 'savePalette', 'openPaletteFolder', 'refreshPalettes'],
  layers: ['newLayer', 'createLayerGroup', 'newTilemapLayer', 'newFreeTileLayer', 'newBackgroundLayer', 'createLinkedLayer', 'convertLayerToBackground', 'convertLayerToTilemap', 'convertLayerToRaster', 'openLayerProperties', 'toggleClippingMask', 'toggleSelectedLayerVisibility', 'toggleSelectedLayerLock', 'toggleSelectedGroupCollapsed', 'toggleLayerMask', 'toggleGroupMask', 'openLayerStyles', 'toggleLayerStyles', 'copyLayerStyles', 'pasteLayerStyles', 'clearLayerStyles', 'duplicateLayer', 'mergeLayerDown', 'mergeSelectedLayers', 'mergeLayerGroup', 'mergeVisibleLayers', 'ungroupLayers', 'openLayerSettings'],
  animation: ['toggleAnimationPlayback', 'toggleOnionSkin', 'animationPlaybackOnce', 'animationPlaybackAll', 'animationPlaybackTag', 'toggleAnimationReturnToStart', 'animationPlaybackSpeed025', 'animationPlaybackSpeed050', 'animationPlaybackSpeed100', 'animationPlaybackSpeed150', 'animationPlaybackSpeed200', 'animationPlaybackSpeed300', 'previousAnimationFrame', 'nextAnimationFrame', 'addAnimationFrame', 'addLinkedAnimationFrame', 'addBlankAnimationFrame', 'deleteAnimationFrame', 'enableAnimationFrames', 'disableAnimationFrames', 'toggleAnimationFramesDisabled', 'copyAnimationCel', 'copyAnimationFrames', 'pasteAnimationFrames', 'pasteAnimationCels', 'copyAnimationMasks', 'pasteAnimationMasks', 'connectAnimationCels', 'disconnectAnimationCels', 'connectAnimationMasks', 'disconnectAnimationMasks', 'toggleAnimationMask', 'createAnimationLoopSection', 'openAnimationFrameProperties', 'playAnimationLoopSection', 'openAnimationLoopSectionProperties', 'deleteAnimationLoopSection', 'openAnimationCelProperties'],
  view: ['relativeLuminance', 'toggleGrid', 'toggleCustomGrid', 'toggleIsoView', 'toggleSliceOutlines', 'openGridSettings', 'openIsoViewSettings', 'tileRepeatOff', 'tileRepeatBoth', 'tileRepeatX', 'tileRepeatY', 'mirrorView', 'mirrorViewVertical', 'rotateViewClockwise90', 'rotateViewCounterClockwise90', 'viewZoom100', 'viewZoom200', 'viewZoom400', 'viewZoom800', 'viewZoom3200', 'resetView'],
  interface: ['popupColorPanel', 'popupPalettePanel', 'popupLayersPanel', 'popupPreviewPanel', 'popupTilesetPanel', 'popupBrushLibraryPanel', 'toggleFullscreen', 'toggleColorPanel', 'togglePalettePanel', 'toggleLayersPanel', 'togglePreviewPanel', 'toggleTilesetPanel', 'toggleBrushLibraryPanel', 'toggleTimeline', 'toolRailLeft', 'toolRailRight', 'toolRailTop', 'toolRailBottom', 'saveWorkspaceLayout', 'resetWorkspaceLayout', 'openWorkspaceManager', 'advancedMode', 'openShortcutSettings', 'openPreferences'],
  tools: [...TOOL_SHORTCUT_GROUP, 'brushShapeRound', 'brushShapeSquare', 'brushShapeLine', 'togglePerfectPixels', 'toggleContiguous', 'toggleSmartClosure', 'toggleRoundedCorners', 'toggleFixedRatio', 'toggleMoveAutoSelect', 'toggleSymmetryHorizontal', 'toggleSymmetryVertical', 'toggleSymmetryDiagonalUp', 'toggleSymmetryDiagonalDown', 'toggleSymmetryRotational', 'resetSymmetryCenter', 'brushSizeDecrease', 'brushSizeIncrease'],
  tiles: ['tilemapModeEdit', 'tilemapModeCreate', 'tilemapModeHybrid', 'tilemapModePaint', 'freeTileModeEdit', 'freeTileModePaint', 'addFreeTileSource', 'deleteTilesetSelection', 'openFreeTileSourceProperties', 'showOnlyFreeTileInstance', 'openFreeTileInstanceProperties', 'rotateFreeTileInstance90', 'mirrorFreeTileInstanceHorizontal', 'mirrorFreeTileInstanceVertical', 'deleteFreeTileInstances'],
  brushes: ['importBrushImage', 'createBrushFolder', 'openBrushFolder', 'refreshBrushLibrary', 'brushLibraryParentFolder', 'brushSwatchSmall', 'brushSwatchMedium', 'brushSwatchLarge', 'deleteBrushSelection'],
  modifiers: ['brushSizeAdjust', 'brushSizeWheelAdjust', 'lineConnectionMode', 'constrainLineDirections', 'copySelectionContent', 'addToSelection', 'proportionalSelectionTransform', 'integerSelectionScale', 'snapSelectionRotation', 'copyLayerOnDrag', 'constrainAxis', 'snapViewRotation', 'resetViewRotation'],
  help: ['openComponentLibrary', 'openLatestRelease', 'openAbout']
} as const satisfies Record<string, ReadonlyArray<ShortcutId>>

export type ShortcutGroupId = keyof typeof SHORTCUT_GROUPS
