// Compatibility entry point. Algorithms depend on the shared pixel-edit kernel.
export { clampSelection, clampSelectionMask, BrushGradientSample, BrushMaskPoint, interpolateBrushAngle, brushStampDimensions, imageBrushCoverageAt, brushTextureContains } from './tools-pixel-edit'
export { inheritBrushPaintBaseline, normalizeSelection, paintSquare, BrushLineGradient, paintBrush, BrushLineDynamics, brushPathStampPoints, brushStampAnchor, brushStrokeInvalidationRects, imageBrushContainsAt, SolidBrushPreviewRowSpan, solidBrushPreviewRowSpans, solidBrushStampDifferenceRects, brushMaskOffsets, paintLine, paintBrushPath } from './tools-brush'
export { PixelPathPoint, appendPerfectPixelSegment, perfectPixelPathPoints, paintShape, selectionMaskPixelPoints, filledShapePathPixelPoints, filledPolygonPathPixelPoints, lineShapePixelPoints, bezierCurvePixelPoints, paintShapePixelPoints, shapeContainsPixel, shapePixelPoints, shapeBoundaryPixelPoints, rotatedShapePixelPoints } from './tools-shapes'
export { OutlinePixelSample, outlinePixelSamples, outlinePixelIndices, outlineSelection, outlineSelectionBoundary, antiAliasSelection } from './tools-outline'
export { PixelOperationProfiler, FloodFillRegionOptions, floodFill, floodFillSymmetric, clearSelection, fillSelectionOrCanvas, replaceLayerColor } from './tools-fill'
export { SelectionTransformSource, flipSelectionTransformSource, SelectionTranslationPreview, SelectionTransformLayerState, captureSelectionTransform, applySelectionTranslationCommit, restoreSelectionTranslationPreview, applySelectionTranslationPreview, selectionTranslationPreviewEdit, selectionTransformPreviewPacked, SelectionTransformPreviewRasterPacked, selectionTransformPreviewRasterPacked, transformRgbaSelectionSurface, selectionTransformPreview, transformSelectionCopy, applySelectionTransform, moveSelection, flipSelection, flipLayer } from './tools-selection-transform'

export { sampleCompositeColor } from './tools-composite-sampling'
