import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createServer } from 'vite'

test('buyer, seller and administrator lifecycle stays isolated and preserves accounting', async () => {
  const memory = new Map()
  globalThis.localStorage = { getItem: (key) => memory.get(key) ?? null, setItem: (key, value) => memory.set(key, String(value)), removeItem: (key) => memory.delete(key) }
  globalThis.window = new EventTarget()
  const server = await createServer({ server: { middlewareMode: true }, appType: 'custom' })
  try {
    const { localAdapter: api, writeStudioUnlocked } = await server.ssrLoadModule('/src/api/local.ts')
    const { unlockLocalAdmin } = await server.ssrLoadModule('/src/api/permissions.ts')
    const seller = await api.auth.register({ name: 'Seller', email: 'seller@example.com', password: 'password123' })
    assert.equal(seller.ok, true)
    writeStudioUnlocked(true, seller.account.id)
    const input = { name: { zh: '测试商品', en: 'Test pack' }, tagline: { zh: '', en: '' }, body: { zh: '', en: '' }, price: 100, category: 'assets', size: '16', formats: ['png'], tags: [] }
    const published = await api.studio.publish(input)
    assert.equal(published.ok, true)
    const productId = published.data.id
    await assert.rejects(api.studio.setPlatformFee(10), /forbidden/)
    assert.equal((await api.orders.create([{ id: productId, name: 'Test', price: 100, quantity: 1 }])).ok, false)
    const buyer = await api.auth.register({ name: 'Buyer', email: 'buyer@example.com', password: 'password123' })
    assert.equal(buyer.ok, true)
    assert.deepEqual(await api.studio.products(), [])
    assert.equal((await api.studio.update(productId, input)).ok, false)
    await assert.rejects(api.studio.unpublish(productId), /forbidden/)
    memory.set('moonsprite-moderation', JSON.stringify({ statuses: { [productId]: { status: 'approved', at: Date.now() + 1 } }, reports: [] }))
    const line = { id: productId, name: 'Test', price: 100, quantity: 1 }
    assert.equal((await api.orders.create([{ ...line, price: 1 }])).ok, false)
    assert.equal((await api.orders.create([{ ...line, quantity: -1 }])).ok, false)
    assert.equal((await api.orders.create([line, line])).ok, false)
    assert.equal((await api.orders.create([line])).ok, true)
    const data = await server.ssrLoadModule('/src/data/store.tsx')
    assert.equal((await data.openTicket({ subject: 'Order help', message: 'Please help with this download.', orderId: 'wrong-order' })).ok, false)
    assert.equal((await data.openTicket({ subject: 'Order help', message: 'Please help with this download.', orderId: (await api.orders.list())[0].id })).ok, true)
    assert.equal((await data.addPayoutMethod({ kind: 'bank', account: '12345678', holder: 'Buyer' })).ok, true)
    assert.equal((await api.orders.create([line])).ok, false)
    assert.equal((await api.studio.ledger()).gross, 0)
    await api.auth.signIn({ email: 'seller@example.com', password: 'password123' })
    assert.deepEqual(data.readTickets(), [])
    assert.deepEqual(data.readPayoutMethods(), [])
    assert.equal((await api.studio.ledger()).available, 92)
    const withdrawal = await api.studio.requestWithdrawal(40, 'test-account')
    assert.equal(withdrawal.ok, true)
    assert.equal((await api.studio.ledger()).available, 52)
    assert.equal((await api.studio.requestWithdrawal(0.4, 'test-account')).ok, false)
    assert.equal(unlockLocalAdmin('admin'), true)
    const ticket = data.readTickets()[0]
    assert.ok(ticket)
    await data.answerTicket(ticket, 'Download is available in your order.')
    await api.studio.setWithdrawalStatus(withdrawal.data.id, 'rejected')
    assert.equal((await api.studio.ledger()).available, 92)
    await assert.rejects(api.studio.setWithdrawalStatus(withdrawal.data.id, 'paid'), /invalid-transition/)
    await api.studio.setPlatformFee(50)
    assert.equal((await api.studio.ledger()).available, 92)
    assert.equal((await api.studio.update(productId, { ...input, price: 120 })).ok, true)
    assert.equal(data.listingStatusOf(productId), 'pending')
    await api.studio.unpublish(productId)
    assert.equal((await api.catalogue.all()).length, 0)
    assert.equal((await api.studio.ledger()).gross, 100)
    await api.auth.signIn({ email: 'buyer@example.com', password: 'password123' })
    assert.equal((await api.orders.list()).length, 1)
    assert.equal(data.readTickets()[0].status, 'answered')
    assert.equal(data.readTickets()[0].reply, 'Download is available in your order.')
    await assert.rejects(data.answerTicket(data.readTickets()[0], 'Unauthorized'), /forbidden/)
    await assert.rejects(api.orders.all(), /forbidden/)
    await api.auth.deleteAccount()
    await api.auth.signIn({ email: 'seller@example.com', password: 'password123' })
    assert.equal((await api.studio.ledger()).gross, 100)
    await api.auth.signOut()
    assert.equal((await api.studio.publish(input)).ok, false)
    assert.equal((await api.studio.ledger()).gross, 0)
  } finally { await server.close() }
})
