// Native dialog copy; locale codes mirror locales/contracts.ts. Unknown locales use Chinese.
pub(super) fn dialog_label(language: Option<&str>, key: &'static str) -> &'static str {
    let index = match language {
        Some("en-US") => 1,
        Some("ja-JP") => 2,
        Some("ko-KR") => 3,
        Some("es-ES") => 4,
        Some("fr-FR") => 5,
        Some("de-DE") => 6,
        Some("pt-BR") => 7,
        Some("ru-RU") => 8,
        _ => 0,
    };
    let labels: [&str; 9] = match key {
        "All files" => [
            "所有文件",
            "All files",
            "すべてのファイル",
            "모든 파일",
            "Todos los archivos",
            "Tous les fichiers",
            "Alle Dateien",
            "Todos os arquivos",
            "Все файлы",
        ],
        "PNG image" => [
            "PNG 图片",
            "PNG image",
            "PNG 画像",
            "PNG 이미지",
            "Imagen PNG",
            "Image PNG",
            "PNG-Bild",
            "Imagem PNG",
            "Изображение PNG",
        ],
        "JPEG image" => [
            "JPEG 图片",
            "JPEG image",
            "JPEG 画像",
            "JPEG 이미지",
            "Imagen JPEG",
            "Image JPEG",
            "JPEG-Bild",
            "Imagem JPEG",
            "Изображение JPEG",
        ],
        "WebP image" => [
            "WebP 图片",
            "WebP image",
            "WebP 画像",
            "WebP 이미지",
            "Imagen WebP",
            "Image WebP",
            "WebP-Bild",
            "Imagem WebP",
            "Изображение WebP",
        ],
        "SVG image" => [
            "SVG 图片",
            "SVG image",
            "SVG 画像",
            "SVG 이미지",
            "Imagen SVG",
            "Image SVG",
            "SVG-Bild",
            "Imagem SVG",
            "Изображение SVG",
        ],
        "BMP image" => [
            "BMP 图片",
            "BMP image",
            "BMP 画像",
            "BMP 이미지",
            "Imagen BMP",
            "Image BMP",
            "BMP-Bild",
            "Imagem BMP",
            "Изображение BMP",
        ],
        "ICO icon" => [
            "ICO 图标",
            "ICO icon",
            "ICO アイコン",
            "ICO 아이콘",
            "Icono ICO",
            "Icône ICO",
            "ICO-Symbol",
            "Ícone ICO",
            "Значок ICO",
        ],
        "GIF animation" => [
            "GIF 动画",
            "GIF animation",
            "GIF アニメーション",
            "GIF 애니메이션",
            "Animación GIF",
            "Animation GIF",
            "GIF-Animation",
            "Animação GIF",
            "GIF-анимация",
        ],
        "MP4 video" => [
            "MP4 视频",
            "MP4 video",
            "MP4 動画",
            "MP4 동영상",
            "Vídeo MP4",
            "Vidéo MP4",
            "MP4-Video",
            "Vídeo MP4",
            "Видео MP4",
        ],
        "WebM video" => [
            "WebM 视频",
            "WebM video",
            "WebM 動画",
            "WebM 동영상",
            "Vídeo WebM",
            "Vidéo WebM",
            "WebM-Video",
            "Vídeo WebM",
            "Видео WebM",
        ],
        "MoonSprite project" => [
            "MoonSprite 工程",
            "MoonSprite project",
            "MoonSprite プロジェクト",
            "MoonSprite 프로젝트",
            "Proyecto MoonSprite",
            "Projet MoonSprite",
            "MoonSprite-Projekt",
            "Projeto MoonSprite",
            "Проект MoonSprite",
        ],
        "Photoshop project" => [
            "Photoshop 工程",
            "Photoshop project",
            "Photoshop プロジェクト",
            "Photoshop 프로젝트",
            "Proyecto Photoshop",
            "Projet Photoshop",
            "Photoshop-Projekt",
            "Projeto Photoshop",
            "Проект Photoshop",
        ],
        "Aseprite project" => [
            "Aseprite 工程",
            "Aseprite project",
            "Aseprite プロジェクト",
            "Aseprite 프로젝트",
            "Proyecto Aseprite",
            "Projet Aseprite",
            "Aseprite-Projekt",
            "Projeto Aseprite",
            "Проект Aseprite",
        ],
        "Aseprite project (.ase)" => [
            "Aseprite 工程 (.ase)",
            "Aseprite project (.ase)",
            "Aseprite プロジェクト (.ase)",
            "Aseprite 프로젝트 (.ase)",
            "Proyecto Aseprite (.ase)",
            "Projet Aseprite (.ase)",
            "Aseprite-Projekt (.ase)",
            "Projeto Aseprite (.ase)",
            "Проект Aseprite (.ase)",
        ],
        "Aseprite project (.aseprite)" => [
            "Aseprite 工程 (.aseprite)",
            "Aseprite project (.aseprite)",
            "Aseprite プロジェクト (.aseprite)",
            "Aseprite 프로젝트 (.aseprite)",
            "Proyecto Aseprite (.aseprite)",
            "Projet Aseprite (.aseprite)",
            "Aseprite-Projekt (.aseprite)",
            "Projeto Aseprite (.aseprite)",
            "Проект Aseprite (.aseprite)",
        ],
        "Aseprite files" => [
            "Aseprite 文件",
            "Aseprite files",
            "Aseprite ファイル",
            "Aseprite 파일",
            "Archivos Aseprite",
            "Fichiers Aseprite",
            "Aseprite-Dateien",
            "Arquivos Aseprite",
            "Файлы Aseprite",
        ],
        "Photoshop files" => [
            "Photoshop 文件",
            "Photoshop files",
            "Photoshop ファイル",
            "Photoshop 파일",
            "Archivos Photoshop",
            "Fichiers Photoshop",
            "Photoshop-Dateien",
            "Arquivos Photoshop",
            "Файлы Photoshop",
        ],
        "All supported files" => [
            "所有支持的文件",
            "All supported files",
            "対応するすべてのファイル",
            "지원되는 모든 파일",
            "Todos los archivos compatibles",
            "Tous les fichiers pris en charge",
            "Alle unterstützten Dateien",
            "Todos os arquivos compatíveis",
            "Все поддерживаемые файлы",
        ],
        "Images" => [
            "图片",
            "Images",
            "画像",
            "이미지",
            "Imágenes",
            "Images",
            "Bilder",
            "Imagens",
            "Изображения",
        ],
        "Brush images" => [
            "笔刷图片",
            "Brush images",
            "ブラシ画像",
            "브러시 이미지",
            "Imágenes de pincel",
            "Images de pinceau",
            "Pinselbilder",
            "Imagens de pincel",
            "Изображения кистей",
        ],
        "PNG palette image" => [
            "PNG 色板图像",
            "PNG palette image",
            "PNG パレット画像",
            "PNG 팔레트 이미지",
            "Imagen de paleta PNG",
            "Image de palette PNG",
            "PNG-Palettenbild",
            "Imagem de paleta PNG",
            "PNG-изображение палитры",
        ],
        "MoonSprite shortcut settings" => [
            "MoonSprite 快捷键设置",
            "MoonSprite shortcut settings",
            "MoonSprite ショートカット設定",
            "MoonSprite 단축키 설정",
            "Atajos de MoonSprite",
            "Raccourcis de MoonSprite",
            "MoonSprite-Tastenkürzel",
            "Atalhos do MoonSprite",
            "Сочетания клавиш MoonSprite",
        ],
        "MoonSprite theme" => [
            "MoonSprite 主题",
            "MoonSprite theme",
            "MoonSprite テーマ",
            "MoonSprite 테마",
            "Tema de MoonSprite",
            "Thème MoonSprite",
            "MoonSprite-Design",
            "Tema do MoonSprite",
            "Тема MoonSprite",
        ],
        "MoonSprite usage statistics" => [
            "MoonSprite 使用统计",
            "MoonSprite usage statistics",
            "MoonSprite 使用統計",
            "MoonSprite 사용 통계",
            "Estadísticas de uso de MoonSprite",
            "Statistiques d’utilisation de MoonSprite",
            "MoonSprite-Nutzungsstatistik",
            "Estatísticas de uso do MoonSprite",
            "Статистика использования MoonSprite",
        ],
        "Extension data" => [
            "扩展数据",
            "Extension data",
            "拡張機能のデータ",
            "확장 기능 데이터",
            "Datos de extensión",
            "Données d’extension",
            "Erweiterungsdaten",
            "Dados da extensão",
            "Данные расширения",
        ],
        "Invalid export file name." => [
            "导出文件名无效。",
            "Invalid export file name.",
            "エクスポートするファイル名が無効です。",
            "내보낼 파일 이름이 잘못되었습니다.",
            "Nombre de archivo de exportación no válido.",
            "Nom de fichier d’exportation invalide.",
            "Ungültiger Exportdateiname.",
            "Nome de arquivo de exportação inválido.",
            "Недопустимое имя экспортируемого файла.",
        ],
        "Invalid export file extension." => [
            "导出文件扩展名无效。",
            "Invalid export file extension.",
            "エクスポートするファイルの拡張子が無効です。",
            "내보낼 파일 확장자가 잘못되었습니다.",
            "Extensión de archivo de exportación no válida.",
            "Extension de fichier d’exportation invalide.",
            "Ungültige Exportdateiendung.",
            "Extensão de arquivo de exportação inválida.",
            "Недопустимое расширение экспортируемого файла.",
        ],
        _ => return key,
    };
    labels[index]
}

#[cfg(test)]
mod tests {
    use super::dialog_label;
    #[test]
    fn every_dialog_label_covers_all_registered_languages() {
        let keys = [
            "PNG image",
            "JPEG image",
            "WebP image",
            "SVG image",
            "BMP image",
            "ICO icon",
            "GIF animation",
            "MP4 video",
            "WebM video",
            "MoonSprite project",
            "Photoshop project",
            "Aseprite project",
            "Aseprite project (.ase)",
            "Aseprite project (.aseprite)",
            "Aseprite files",
            "Photoshop files",
            "All supported files",
            "Images",
            "Brush images",
            "PNG palette image",
            "MoonSprite shortcut settings",
            "MoonSprite theme",
            "MoonSprite usage statistics",
            "Extension data",
            "Invalid export file name.",
            "Invalid export file extension.",
        ];
        for key in keys {
            let chinese = dialog_label(Some("zh-CN"), key);
            assert_eq!(dialog_label(None, key), chinese);
            assert_eq!(dialog_label(Some("invalid"), key), chinese);
            assert_eq!(dialog_label(Some("en-US"), key), key);
            for locale in [
                "ja-JP", "ko-KR", "es-ES", "fr-FR", "de-DE", "pt-BR", "ru-RU",
            ] {
                let label = dialog_label(Some(locale), key);
                assert!(!label.is_empty());
                assert_ne!(label, chinese, "{locale}: {key}");
            }
        }
    }
}
