import type { DocumentSession } from '@/store/workspace'
import { TOOL_DEFINITIONS } from './editor-tools'
import { CYCLING_TOOL_SHORTCUT_IDS } from '@/core/shortcuts'
export const activeToolShortcutFor = (currentSession: DocumentSession | null): (typeof CYCLING_TOOL_SHORTCUT_IDS)[number] | null => !currentSession ? null
        : currentSession.tool === 'selection'
        ? currentSession.selectionKind === 'ellipse' ? 'tool.selection.ellipse'
        : currentSession.selectionKind === 'lasso' ? 'lasso'
        : currentSession.selectionKind === 'polygon-lasso' ? 'polygonLasso'
        : currentSession.selectionKind === 'magic' ? 'magic'
        : 'tool.selection'
        : currentSession.tool === 'fill'
        ? currentSession.fillKind === 'gradient' ? 'tool.fill.gradient' : 'tool.fill'
        : currentSession.tool === 'shape'
        ? currentSession.shapeKind === 'rectangle-outline' ? 'tool.shape.rectangleOutline'
        : currentSession.shapeKind === 'rectangle' ? 'tool.shape.rectangle'
        : currentSession.shapeKind === 'ellipse-outline' ? 'tool.shape.ellipseOutline'
        : currentSession.shapeKind === 'ellipse' ? 'tool.shape.ellipse'
        : currentSession.shapeKind === 'freeform' ? 'tool.shape.freeform'
        : currentSession.shapeKind === 'polygon' ? 'tool.shape.polygon'
        : 'tool.shape'
        : currentSession.tool === 'line'
        ? currentSession.lineKind === 'curve' ? 'tool.curve' : 'tool.line'
        : currentSession.tool === 'move' && currentSession.moveKind === 'slice'
        ? 'tool.slice'
        : TOOL_DEFINITIONS.find((tool) => tool.id === currentSession.tool)?.shortcutId as (typeof CYCLING_TOOL_SHORTCUT_IDS)[number] | undefined ?? null
